title: Da Vinci
description: >
  Da Vinci Dome
email: info@burociviel.nl
app_url: https://civilsource.github.io/DavinciDome/app/
github:
  repository_url: https://github.com/CivilSource/DavinciDome
  repository_name: DavinciDome
